
prefix = /usr/local
exec_prefix = /usr/local
bindir = /usr/local/bin
libexecdir = /usr/local/libexec
localstatedir = /usr/local/var
sysconfdir = /usr/local/etc
datarootdir = /usr/local/share
datadir = /usr/local/share
mandir = /usr/local/share/man
develmode = false
SHELL = /bin/bash
BASH = /bin/bash
DASH = /bin/dash
XDG_OPEN = /usr/bin/xdg-open
FIREFOX = 
BROWSER = /usr/bin/xdg-open
GIT = /usr/bin/git
RONN = 
SHOCCO = 
